# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-09 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170909_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
    ]
